spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
#          url contains config directories on local
          search-locations: classpath:/configurations
server:
  port: 8888